<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

$this->factories['service_container']['Tests\\Fixtures\\AppBundle\\DataTable\\Adapter\\CustomORMAdapter'] = function () {
    // Returns the private 'Tests\Fixtures\AppBundle\DataTable\Adapter\CustomORMAdapter' autowired service.

    return new \Tests\Fixtures\AppBundle\DataTable\Adapter\CustomORMAdapter(($this->services['doctrine'] ?? $this->getDoctrineService()));
};

return $this->factories['service_container']['Tests\\Fixtures\\AppBundle\\DataTable\\Adapter\\CustomORMAdapter']();
