<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'datatables.column_locator' shared service.

return $this->privates['datatables.column_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Omines\\DataTablesBundle\\Column\\TwigColumn' => [false, 'Omines\\DataTablesBundle\\Column\\TwigColumn', 'getTwigColumnService.php', true],
], [
    'Omines\\DataTablesBundle\\Column\\TwigColumn' => '?',
]);
