<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Omines\DataTablesBundle\DataTableFactory' shared autowired service.

return $this->services['Omines\\DataTablesBundle\\DataTableFactory'] = new \Omines\DataTablesBundle\DataTableFactory($this->parameters['datatables.config'], ($this->privates['Omines\\DataTablesBundle\\Twig\\TwigRenderer'] ?? $this->load('getTwigRendererService.php')), ($this->privates['Omines\\DataTablesBundle\\DependencyInjection\\Instantiator'] ?? $this->load('getInstantiatorService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
