<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXwfC1JS\tmpTests_Fixtures_AppKernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXwfC1JS/tmpTests_Fixtures_AppKernelTestContainer.php') {
    touch(__DIR__.'/ContainerXwfC1JS.legacy');

    return;
}

if (!\class_exists(tmpTests_Fixtures_AppKernelTestContainer::class, false)) {
    \class_alias(\ContainerXwfC1JS\tmpTests_Fixtures_AppKernelTestContainer::class, tmpTests_Fixtures_AppKernelTestContainer::class, false);
}

return new \ContainerXwfC1JS\tmpTests_Fixtures_AppKernelTestContainer([
    'container.build_hash' => 'XwfC1JS',
    'container.build_id' => '2954406f',
    'container.build_time' => 1599845687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXwfC1JS');
