<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'datatables.type_locator' shared service.

return $this->privates['datatables.type_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Tests\\Fixtures\\AppBundle\\DataTable\\Type\\ServicePersonTableType' => ['privates', 'Tests\\Fixtures\\AppBundle\\DataTable\\Type\\ServicePersonTableType', 'getServicePersonTableTypeService.php', true],
], [
    'Tests\\Fixtures\\AppBundle\\DataTable\\Type\\ServicePersonTableType' => '?',
]);
