<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Omines\DataTablesBundle\DependencyInjection\Instantiator' shared autowired service.

return $this->privates['Omines\\DataTablesBundle\\DependencyInjection\\Instantiator'] = new \Omines\DataTablesBundle\DependencyInjection\Instantiator(['Omines\\DataTablesBundle\\Adapter\\AdapterInterface' => ($this->privates['datatables.adapter_locator'] ?? $this->load('getDatatables_AdapterLocatorService.php')), 'Omines\\DataTablesBundle\\Column\\AbstractColumn' => ($this->privates['datatables.column_locator'] ?? $this->load('getDatatables_ColumnLocatorService.php')), 'Omines\\DataTablesBundle\\DataTableTypeInterface' => ($this->privates['datatables.type_locator'] ?? $this->load('getDatatables_TypeLocatorService.php'))]);
