<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

$this->factories['service_container']['Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter'] = function () {
    // Returns the private 'Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter' autowired service.

    return new \Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter(($this->services['doctrine'] ?? $this->getDoctrineService()));
};

return $this->factories['service_container']['Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter']();
