<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Tests\Fixtures\AppBundle\DataTable\Type\ServicePersonTableType' shared autowired service.

return $this->privates['Tests\\Fixtures\\AppBundle\\DataTable\\Type\\ServicePersonTableType'] = new \Tests\Fixtures\AppBundle\DataTable\Type\ServicePersonTableType(($this->services['router'] ?? $this->getRouterService()));
