<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

$this->factories['service_container']['Omines\\DataTablesBundle\\Column\\TwigColumn'] = function () {
    // Returns the private 'Omines\DataTablesBundle\Column\TwigColumn' autowired service.

    return new \Omines\DataTablesBundle\Column\TwigColumn(($this->services['twig'] ?? $this->getTwigService()));
};

return $this->factories['service_container']['Omines\\DataTablesBundle\\Column\\TwigColumn']();
